name: Futuring
favicon: null
layout_spectrum: 0.9181455876678228
typography_spectrum: 0.217872193781659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3029646226204932
  lightness: 0.10834182216785848
  saturation: 0.733831818215549
  rhythmicContrast: 0.2269153967499733
purpose: []
